export type Listing = {
  id: string;
  host_id: string;
  structure_name: string;
  address: string;
  parking_type: string;
  price_per_hour: number;
  amenities: string[];
  images: any[];
  available_from: string;
  available_until: string;
  is_active: boolean;
  is_saved?: boolean;
  created_at: string;
  updated_at: string;
  title: string;
  description: string;
  perks: string[];
  incentives: string[];
  sub_heading?: string[];
  is_guest_favorite?: boolean;
  rating?: number | null;
  review_count?: number;
  host_name?: string;
  host_type?: string;
  is_popular?: boolean;
  original_price?: number | null;
};
